//! Full AMI pipeline orchestrator: build → test → cluster-test → promote (or rollback).
//!
//! Replaces the shell script in substrate's `mkAmiBuildPipeline` with a
//! single Rust binary. Packer handles SSH, instance lifecycle, and cleanup.
//! This module orchestrates the Packer invocations and post-build actions.
//!
//! Configuration is read from a YAML file generated by Nix (shikumi pattern:
//! Nix option → YAML config file → Rust reads config). The `--config` flag
//! points to the pipeline config.

use anyhow::{bail, Context, Result};
use clap::Args;
use serde::Deserialize;
use std::path::PathBuf;
use std::process::Command;
use tracing::{error, info, warn};

#[derive(Args)]
pub struct PipelineRunArgs {
    /// Path to pipeline configuration YAML
    #[arg(long)]
    pub config: PathBuf,
}

#[derive(Deserialize)]
pub struct PipelineConfig {
    pub build_template: PathBuf,
    pub test_template: PathBuf,
    pub ssm: String,
    pub ami_name: String,
    #[serde(default = "default_region")]
    pub region: String,
    #[serde(default)]
    pub cluster_test: Option<ClusterTestRef>,
    #[serde(default = "default_manifest")]
    pub manifest: PathBuf,
}

#[derive(Deserialize)]
pub struct ClusterTestRef {
    pub config: PathBuf,
}

fn default_region() -> String {
    "us-east-1".into()
}
fn default_manifest() -> PathBuf {
    PathBuf::from("packer-manifest.json")
}

pub async fn run(args: PipelineRunArgs) -> Result<()> {
    let config_content = std::fs::read_to_string(&args.config)
        .with_context(|| format!("failed to read pipeline config: {}", args.config.display()))?;
    let config: PipelineConfig = serde_yaml::from_str(&config_content)
        .context("failed to parse pipeline config YAML")?;

    // Validate inputs
    if !config.build_template.exists() {
        bail!(
            "Build template not found: {}",
            config.build_template.display()
        );
    }
    if !config.test_template.exists() {
        bail!(
            "Test template not found: {}",
            config.test_template.display()
        );
    }

    let total_phases = if config.cluster_test.is_none() { 4 } else { 5 };

    // Validate AWS credentials early
    let aws_config = crate::aws::load_config(&config.region).await;
    let arn = crate::aws::validate_credentials(&aws_config).await?;
    info!("Pipeline starting as {arn}");

    let github_token = std::env::var("GITHUB_TOKEN").unwrap_or_default();
    let build_tpl = config.build_template.to_string_lossy();
    let test_tpl = config.test_template.to_string_lossy();
    let manifest_path = config.manifest.to_string_lossy().to_string();

    // ── Phase 1: Build AMI ──────────────────────────────────────
    info!("[1/{total_phases}] Building AMI from base NixOS image");
    run_packer_init(&build_tpl)?;
    run_packer_build(&build_tpl, &[format!("github_token={github_token}")])?;

    // ── Phase 2: Extract AMI ID ─────────────────────────────────
    info!("[2/{total_phases}] Extracting AMI ID from manifest");
    let ami_id = crate::aws::parse_packer_manifest(&manifest_path)?;
    info!("Built AMI: {ami_id}");

    // ── Phase 3: Single-node smoke test (Packer) ────────────────
    info!("[3/{total_phases}] Running single-node integration test on {ami_id}");
    run_packer_init(&test_tpl)?;
    let test_result = run_packer_build(&test_tpl, &[format!("source_ami={ami_id}")]);

    if let Err(e) = test_result {
        error!("Single-node test FAILED: {e:#}");
        deregister_and_fail(&aws_config, &config.ami_name, &manifest_path, &ami_id).await?;
    }

    // ── Phase 4: Multi-node cluster test ────────────────────────
    if let Some(ref ct) = config.cluster_test {
        info!("[4/{total_phases}] Running multi-node cluster integration test on {ami_id}");
        let cluster_args = crate::cluster_test::ClusterTestArgs {
            config: ct.config.clone(),
            ami_id: ami_id.clone(),
        };
        if let Err(e) = crate::cluster_test::run(cluster_args).await {
            error!("Cluster test FAILED: {e:#}");
            deregister_and_fail(&aws_config, &config.ami_name, &manifest_path, &ami_id).await?;
        }
    }

    // ── Phase 5: Promote ────────────────────────────────────────
    let promote_phase = if config.cluster_test.is_none() { 4 } else { 5 };
    info!("[{promote_phase}/{total_phases}] Promoting AMI {ami_id} to {}", config.ssm);
    let ssm_client = aws_sdk_ssm::Client::new(&aws_config);
    crate::aws::put_ssm_parameter(&ssm_client, &config.ssm, &ami_id).await?;

    cleanup_manifest(&manifest_path);
    info!(
        "Pipeline complete — AMI {ami_id} promoted to {}",
        config.ssm
    );

    Ok(())
}

async fn deregister_and_fail(
    config: &aws_config::SdkConfig,
    ami_name: &str,
    manifest_path: &str,
    ami_id: &str,
) -> Result<()> {
    info!("Deregistering failed AMI: {ami_id}");
    let ec2 = aws_sdk_ec2::Client::new(config);
    match crate::rotate::run_rotate(&ec2, ami_name).await {
        Ok(()) => info!("Failed AMI deregistered"),
        Err(re) => warn!("AMI deregistration also failed: {re}"),
    }
    cleanup_manifest(manifest_path);
    bail!("AMI pipeline failed — AMI deregistered");
}

fn run_packer_init(template: &str) -> Result<()> {
    let status = Command::new("packer")
        .args(["init", template])
        .status()
        .context("failed to execute packer init")?;
    if !status.success() {
        bail!("packer init failed for {template}");
    }
    Ok(())
}

fn run_packer_build(template: &str, vars: &[String]) -> Result<()> {
    let mut cmd = Command::new("packer");
    cmd.arg("build");
    for var in vars {
        cmd.args(["-var", var]);
    }
    cmd.arg(template);
    let status = cmd.status().context("failed to execute packer build")?;
    if !status.success() {
        bail!("packer build failed for {template}");
    }
    Ok(())
}

fn cleanup_manifest(path: &str) {
    if std::path::Path::new(path).exists() {
        if let Err(e) = std::fs::remove_file(path) {
            warn!("Failed to remove manifest: {e}");
        }
    }
}
