//! Full AMI pipeline orchestrator: build → test → cluster-test → promote (or rollback).
//!
//! Replaces the shell script in substrate's `mkAmiBuildPipeline` with a
//! single Rust binary. Packer handles SSH, instance lifecycle, and cleanup.
//! This module orchestrates the Packer invocations and post-build actions.
//!
//! Configuration is read from a YAML file generated by Nix (shikumi pattern:
//! Nix option → YAML config file → Rust reads config). The `--config` flag
//! points to the pipeline config.

use anyhow::{bail, Context, Result};
use clap::Args;
use serde::Deserialize;
use std::path::PathBuf;
use std::process::Command;
use tracing::{error, info, warn};

use crate::attic;

#[derive(Args)]
pub struct PipelineRunArgs {
    /// Path to pipeline configuration YAML
    #[arg(long)]
    pub config: PathBuf,
}

#[derive(Deserialize)]
pub struct PipelineConfig {
    pub build_template: PathBuf,
    pub test_template: PathBuf,
    pub ssm: String,
    pub ami_name: String,
    #[serde(default = "default_region")]
    pub region: String,
    #[serde(default)]
    pub cluster_test: Option<ClusterTestRef>,
    #[serde(default = "default_manifest")]
    pub manifest: PathBuf,
    #[serde(default)]
    pub attic: Option<attic::AtticConfig>,
}

#[derive(Deserialize)]
pub struct ClusterTestRef {
    pub config: PathBuf,
}

fn default_region() -> String {
    "us-east-1".into()
}
fn default_manifest() -> PathBuf {
    PathBuf::from("packer-manifest.json")
}

// ---------------------------------------------------------------------------
// Pipeline orchestrator
// ---------------------------------------------------------------------------

pub async fn run(args: PipelineRunArgs) -> Result<()> {
    let config_content = std::fs::read_to_string(&args.config)
        .with_context(|| format!("failed to read pipeline config: {}", args.config.display()))?;
    let config: PipelineConfig = serde_yaml::from_str(&config_content)
        .context("failed to parse pipeline config YAML")?;

    // Validate inputs
    if !config.build_template.exists() {
        bail!(
            "Build template not found: {}",
            config.build_template.display()
        );
    }
    if !config.test_template.exists() {
        bail!(
            "Test template not found: {}",
            config.test_template.display()
        );
    }

    let total_phases = if config.cluster_test.is_none() { 4 } else { 5 };

    // Validate AWS credentials early
    let aws_config = crate::aws::load_config(&config.region).await;
    let arn = crate::aws::validate_credentials(&aws_config).await?;
    info!("Pipeline starting as {arn}");

    // ── Attic ephemeral cache (optional) ────────────────────────
    let mut attic_res: Option<attic::AtticResources> = None;
    if let Some(ref attic_cfg) = config.attic {
        info!("[attic] Booting ephemeral cache from {}", attic_cfg.ssm);
        let ec2_client = aws_sdk_ec2::Client::new(&aws_config);
        let ssm_client = aws_sdk_ssm::Client::new(&aws_config);
        match attic::attic_boot(&ec2_client, &ssm_client, attic_cfg).await {
            Ok(res) => match attic::attic_wait_healthy(&res.public_ip, 180).await {
                Ok(()) => {
                    attic_res = Some(res);
                }
                Err(e) => {
                    warn!("[attic] Health check failed (degrading without cache): {e:#}");
                    if let Err(te) = attic::attic_teardown(&ec2_client, &res).await {
                        warn!("[attic] Teardown of unhealthy instance also failed: {te:#}");
                    }
                }
            },
            Err(e) => {
                warn!("[attic] Boot failed (degrading without cache): {e:#}");
            }
        }
    }

    // Run the pipeline phases, capturing the result so Attic cleanup always runs.
    let pipeline_result =
        run_pipeline_phases(&config, &aws_config, &attic_res, total_phases).await;

    // ── Attic snapshot + teardown (ALWAYS -- cache grows richer) ─
    if let Some(ref res) = attic_res {
        let attic_cfg = config.attic.as_ref().expect("attic_res set implies config.attic is Some");
        let ec2_client = aws_sdk_ec2::Client::new(&aws_config);
        let ssm_client = aws_sdk_ssm::Client::new(&aws_config);
        if let Err(e) = attic::attic_snapshot(&ec2_client, &ssm_client, &res.instance_id, &attic_cfg.ssm).await {
            warn!("[attic] Snapshot failed (non-fatal): {e:#}");
        }
        if let Err(e) = attic::attic_teardown(&ec2_client, res).await {
            warn!("[attic] Teardown failed: {e:#}");
        }
    }

    pipeline_result
}

/// Inner pipeline phases, factored out so Attic cleanup always runs regardless
/// of success or failure.
async fn run_pipeline_phases(
    config: &PipelineConfig,
    aws_config: &aws_config::SdkConfig,
    attic_res: &Option<attic::AtticResources>,
    total_phases: usize,
) -> Result<()> {
    let github_token = std::env::var("GITHUB_TOKEN").unwrap_or_default();
    let build_tpl = config.build_template.to_string_lossy();
    let test_tpl = config.test_template.to_string_lossy();
    let manifest_path = config.manifest.to_string_lossy().to_string();

    // ── Phase 1: Build AMI ──────────────────────────────────────
    info!("[1/{total_phases}] Building AMI from base NixOS image");
    run_packer_init(&build_tpl)?;

    let mut build_vars = vec![format!("github_token={github_token}")];
    if let Some(ref res) = *attic_res {
        let cache_name = &config
            .attic
            .as_ref()
            .expect("attic_res set implies config.attic is Some")
            .cache_name;
        // Use private IP -- the build instance is in the same VPC as the Attic server
        build_vars.push(format!(
            "attic_url=http://{}:8080/{cache_name}",
            res.private_ip
        ));
        info!("[attic] Passing substituter URL to Packer build (private IP)");
    }
    run_packer_build(&build_tpl, &build_vars)?;

    // ── Phase 2: Extract AMI ID ─────────────────────────────────
    info!("[2/{total_phases}] Extracting AMI ID from manifest");
    let ami_id = crate::aws::parse_packer_manifest(&manifest_path)?;
    info!("Built AMI: {ami_id}");

    // ── Phase 3: Single-node smoke test (Packer) ────────────────
    info!("[3/{total_phases}] Running single-node integration test on {ami_id}");
    run_packer_init(&test_tpl)?;
    let test_result = run_packer_build(&test_tpl, &[format!("source_ami={ami_id}")]);

    if let Err(e) = test_result {
        error!("Single-node test FAILED: {e:#}");
        deregister_and_fail(aws_config, &config.ami_name, &manifest_path, &ami_id).await?;
    }

    // ── Phase 4: Multi-node cluster test ────────────────────────
    if let Some(ref ct) = config.cluster_test {
        info!("[4/{total_phases}] Running multi-node cluster integration test on {ami_id}");
        let cluster_args = crate::cluster_test::ClusterTestArgs {
            config: ct.config.clone(),
            ami_id: ami_id.clone(),
        };
        if let Err(e) = crate::cluster_test::run(cluster_args).await {
            error!("Cluster test FAILED: {e:#}");
            deregister_and_fail(aws_config, &config.ami_name, &manifest_path, &ami_id).await?;
        }
    }

    // ── Phase 5: Promote ────────────────────────────────────────
    let promote_phase = if config.cluster_test.is_none() { 4 } else { 5 };
    info!("[{promote_phase}/{total_phases}] Promoting AMI {ami_id} to {}", config.ssm);
    let ssm_client = aws_sdk_ssm::Client::new(aws_config);
    crate::aws::put_ssm_parameter(&ssm_client, &config.ssm, &ami_id).await?;

    cleanup_manifest(&manifest_path);
    info!(
        "Pipeline complete -- AMI {ami_id} promoted to {}",
        config.ssm
    );

    Ok(())
}

async fn deregister_and_fail(
    config: &aws_config::SdkConfig,
    ami_name: &str,
    manifest_path: &str,
    ami_id: &str,
) -> Result<()> {
    info!("Deregistering failed AMI: {ami_id}");
    let ec2 = aws_sdk_ec2::Client::new(config);
    match crate::rotate::run_rotate(&ec2, ami_name).await {
        Ok(()) => info!("Failed AMI deregistered"),
        Err(re) => warn!("AMI deregistration also failed: {re}"),
    }
    cleanup_manifest(manifest_path);
    bail!("AMI pipeline failed -- AMI deregistered");
}

fn run_packer_init(template: &str) -> Result<()> {
    let status = Command::new("packer")
        .args(["init", template])
        .status()
        .context("failed to execute packer init")?;
    if !status.success() {
        bail!("packer init failed for {template}");
    }
    Ok(())
}

fn run_packer_build(template: &str, vars: &[String]) -> Result<()> {
    let mut cmd = Command::new("packer");
    cmd.arg("build");
    // On error: clean up the builder instance instead of leaving it running.
    // This prevents orphaned instances when Packer encounters provisioner errors.
    cmd.args(["-on-error=cleanup"]);
    for var in vars {
        cmd.args(["-var", var]);
    }
    cmd.arg(template);
    let status = cmd.status().context("failed to execute packer build")?;
    if !status.success() {
        bail!("packer build failed for {template}");
    }
    Ok(())
}

fn cleanup_manifest(path: &str) {
    if std::path::Path::new(path).exists() {
        if let Err(e) = std::fs::remove_file(path) {
            warn!("Failed to remove manifest: {e}");
        }
    }
}
